server:
  port: 8081
spring:
  application:
    name: service-zuul
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka
zuul:
  routes:
    service-admin:
      path: /api-admin/**
      serviceId: service-admin
    service-user:
      path: /api-user/**
      serviceId: service-user
